version: 2

project_name: rcon-cli
before:
  hooks:
    - go mod download
release:
  replace_existing_artifacts: true
  github:
    owner: Eddict
    name: rcon-cli
builds:
- goos:
  - windows
  goarch:
  - amd64
  main: .
  binary: rcon-cli
  env:
    - CGO_ENABLED=0
archives:
  -
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
    files:
    - LICENSE*
    - README*
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
docker_manifests:
  - name_template: "eddictnl/rcon-cli:latest"
    image_templates:
      - "eddictnl/rcon-cli:{{ .Version }}-amd64"
  - name_template: "eddictnl/rcon-cli:{{ .Version }}"
    image_templates:
      - "eddictnl/rcon-cli:{{ .Version }}-amd64"
