version: 2

project_name: rcon-cli
before:
  hooks:
    - go mod download
release:
  replace_existing_artifacts: true
  github:
    owner: Eddict
    name: rcon-cli
builds:
- goos:
  - windows
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  - "7"
  main: .
  binary: rcon-cli
  env:
    - CGO_ENABLED=0
archives:
  -
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
dockers:
  - image_templates:
      - "eddictnl/rcon-cli:{{ .Version }}-amd64"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
docker_manifests:
  - name_template: "eddictnl/rcon-cli:latest"
    image_templates:
      - "eddictnl/rcon-cli:{{ .Version }}-amd64"
  - name_template: "eddictnl/rcon-cli:{{ .Version }}"
    image_templates:
      - "eddictnl/rcon-cli:{{ .Version }}-amd64"
